set up app.js, models.js and controllers.js for 3rd Ticket(GET api)
jhung2317/nc-games pull request #2
Opened 2023-05-09 14:31 UTC by jhung2317

set up app.js, models.js and controllers.js for 3rd Ticket

2023-05-09 14:45 UTC, johnhutcheon commented on app.js
> +
For the 404 error, we'd want some manual error handling in here. Have a think about how we could use app.use for an end point of * which would return a 404 for any endpoint that doesn't exist. 👍 Hint- We'd use another app.use before the one on line 10 🙂 
We wouldn't need a 22P02 error at this point, so this can be removed, but you can keep the 500 error in there.

2023-05-09 14:45 UTC, johnhutcheon commented on __tests__/app.test.js
> +    })
Could we add a separate describe block with a 404 error test please?

2023-05-09 14:46 UTC, johnhutcheon requested changes
Hi Jason, nice work so far! Please see my feedback and amend the error handling middleware, then add another test. If you could resubmit after you've done this please 🙂

2023-05-10 09:03 UTC, Geo-Beard reviewed
Just one small change - app.get not app.use for your /api/categories endpoint. Otherwise - looks good! Feel free to merge and move on when you've made that change!

2023-05-10 09:18 UTC, merged